<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sysvinel007" name="com.turbopro.customerinvoice.CustomerInvoiceOutside" tests="7" failures="0" timestamp="21 Oct 2017 05:20:33 GMT" time="47.214" errors="1">
  <testcase name="closeCustomerInvoice" time="11.215" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside"/>
  <testcase name="enterCustomerAndTaxTerritory" time="3.421" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside"/>
  <testcase name="clickNewInvoice" time="0.659" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside"/>
  <testcase name="login" time="4.231" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside"/>
  <testcase name="navigatingCustomerInvoice" time="3.554" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside"/>
  <testcase name="addLineItemsAndSaving" time="24.134" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside"/>
  <testcase name="updateProOfCI" time="0.000" classname="com.turbopro.customerinvoice.CustomerInvoiceOutside">
    <error type="org.testng.TestNGException" message="
Method updateProOfCI requires 1 parameters but 0 were supplied in the @Test annotation.">
      <![CDATA[org.testng.TestNGException: 
Method updateProOfCI requires 1 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:191)
	at org.testng.internal.Parameters.createParameters(Parameters.java:127)
	at org.testng.internal.Parameters.createParameters(Parameters.java:376)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- updateProOfCI -->
</testsuite> <!-- com.turbopro.customerinvoice.CustomerInvoiceOutside -->
